### ISSUE TITLE
Script won't load

### ISSUE THREAD

**Issue by Petervandezanden** [jwa107/Photoshop-Export-Layers-to-Files-Fast#100]
I have a problem opening the Photoshop-Export-Layers-toFles-Fast script.
I use Photoshop CC 2017.0.1, most recent update (dec 29 - 2016).
In the screen print you can see what Photoshop reaction is on loading the script.
![script failure](https://cloud.githubusercontent.com/assets/24824920/21542802/e92db558-cdc0-11e6-9bba-e2af9f755970.png)

We all have to rely on this script, since Adobe removed the old Export layers to files script.
Also, I used your script before, and it was outstanding fast.

Peter...

**Comment by jwa107** [comment]
@Petervandezanden Thanks Peter, I don't yet have this current update, but I will try to find some time to update mine and give the script a run and see if I get the same issue. In the meantime, what OS and OS version are you running?

**Comment by jwa107** [comment]
I'm unable to reproduce this, the error code especially does not look related to our code as we do not use HTML
