### ISSUE TITLE
Exporting layers as files, but keeping adjustment layers on top of all of them

### ISSUE THREAD

**Issue by TrylobitBroccoli** [jwa107/Photoshop-Export-Layers-to-Files-Fast#102]
Hi!

So I have 3 layers on top of the layers I want to export: Levels, Hue/Saturation and one layer with white shape. Under those 3 layers are 72 layers with images. I'd like to export each of them as separate file, but each layer while exporting should be exported with the same 3 layers on top.

Is it possible to do so?
I'm more than happy to donate for this feature :)

Thank you in advance!

**Comment by skjorn** [comment]
Hi, try this: put the 72 layers you want to export into a folder/group, select the group, leave the 3 layers above visible, in the export settings dialog choose export selection and it should do the trick I think.

**Comment by TrylobitBroccoli** [comment]
Beautiful, thank you!

**Comment by skjorn** [comment]
You're welcome :-)
