### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Eternyti** [jwa107/Photoshop-Export-Layers-to-Files-Fast#105]
![image](https://user-images.githubusercontent.com/29550956/27299228-a7933ce2-54f9-11e7-9754-cb556f15a778.png)

Was so excited to use the script, then this pops up. Running Windows 7 64bit.
Redownloaded the thing 3 times, no difference. Extracted the files in normally.
I looked at the file's code, on line 939...

![image](https://user-images.githubusercontent.com/29550956/27299366-2d667a50-54fa-11e7-99dc-365aee8cd128.png)

and I have no idea what's wrong with it?? not that I know anything about this sort of code but...
can this be fixed?

**Comment by CloudyChess** [comment]
I also get this error when using the latest version of the script. Windows 10 64bit here. I grabbed an older version of the script from: https://github.com/jwa107/Photoshop-Export-Layers-to-Files-Fast/commit/302c868b2f3185604606983385130aa35a1c2220 and it worked fine. Seems the latest few commits might be causing the issue?

**Comment by RenaudDespinois** [comment]
I'm not one of the devs but it seems somebody forgot to commit his dialog.json...

Quick fix, open and update the dialog.json adding the 2 bold lines. It worked for me...
grpNaming: Group {
				orientation: "row",
				txtNaming: StaticText {text: "Name files:", preferredSize: [80, 20]},
				drdNaming: DropDownList {preferredSize: [140, 20], properties: {items: ["As layers, strip extension", "As layers", "By index from top", "By index from bottom"]}},
				cbNaming: Checkbox {text: "Allow spaces"}
				**radioUnderscore: RadioButton {text: "Underscore delimiter", preferredSize: [80, 20], value: true},
				radioHyphen: RadioButton {text: "Hyphen delimiter", preferredSize: [100, 20]}**

**Comment by jwa107** [comment]
That was my fault. Not sure why git didn't pick up the changes when I pushed everything, but I should've reviewed it all again afterwards. Please try it again and let me know how it goes.
