### ISSUE TITLE
More of a comment than an issue

### ISSUE THREAD

**Issue by albertramsbottom** [jwa107/Photoshop-Export-Layers-to-Files-Fast#109]
We should really be working on the original layer saver script and get it to work in PS CC 2017

This script was fast and had many many more options than this one,

The things that set it apart was the fact that you could save layers with Prefixes and increment the files with hyphens and numbers such as MFOTL395 and it would merge visible and/or selected layers in to files and name them MFOTL395-01.jpg, MFOTL395-02.jpg and so on
 
You could also set it to save selected layers along with the top or bottom most layers, including smart objects and backgrounds
 
Please someone update this script so it works in PS CC 2017, i have it safe if anyone has the talent to do this, it works in CS6 and I think it works in CC 2015
 
I create t-shirt designs and have all the 13 colours of shirt at the bottom of my file and all the smart vector objects above, i can select all 13 blank coloured t-shirts and merge each one with a selected smart vector object and create all the colour variation images or ebay, amazon, my website etc in seconds for each design

**Comment by albertramsbottom** [comment]
Here is the original, no disrespect meant to anyone who has contributed to this project

[Layer Saver.zip](https://github.com/jwa107/Photoshop-Export-Layers-to-Files-Fast/files/1428202/Layer.Saver.zip)

**Comment by jwa107** [comment]
Maybe file an issue with those guys then. We don't work on or have control over other projects.
