### ISSUE TITLE
Batch Convert PSD files to PNG by layer

### ISSUE THREAD

**Issue by Jcan** [jwa107/Photoshop-Export-Layers-to-Files-Fast#117]
Great Script! I have many PSD files in a folder need to convert.
It is possible to batch convert them?
Thank you in advance.

**Comment by jwa107** [comment]
@Jcan This isn't anything this script does. You should use Adobe Bridge to batch convert files.

**Comment by Jcan** [comment]
Thanks for your prompt response! It is possible to integrate your script with http://blog.wp.weightpoint.se/2012/02/02/batch-export-photoshop-psd-files-to-png-the-right-way/?

**Comment by jwa107** [comment]
I'm not sure I'm understanding the request.

Is it:
1) To convert PSDs into PNGs.
2) To run the "layers to PNG script" on a batch of PSD files

**Comment by Jcan** [comment]
@jwa107 
Sorry for my poor English ;-(
My request is to convert layers of PSDs into PNGs in bulk.
