### ISSUE TITLE
Export groups as folders

### ISSUE THREAD

**Issue by skjorn** [jwa107/Photoshop-Export-Layers-to-Files-Fast#17]
Make an option to export the layer tree as a file tree, where layer groups would correspond to folders. 

(Clean up old file tree with the same root folder name? Restart file name indices in sub-folders? Apply file name prefix to folders as well? There's a lot of details to figure out...)

**Comment by mads10000** [comment]
Would incredible usefull. If you want money for it i'll pay.

**Comment by Bahanix** [comment]
Available in this PR #60 :+1:

**Comment by skjorn** [comment]
Done.
