### ISSUE TITLE
I add a new feature : Export  Top-Group as Layer

### ISSUE THREAD

**Issue by finscn** [jwa107/Photoshop-Export-Layers-to-Files-Fast#21]
this feature will make the group which is level 1 (the top level) group to a single image.

I think this feature is useful for somebody.

![new-export](https://cloud.githubusercontent.com/assets/288367/3657868/51b8bdb4-119b-11e4-9b60-85124531998e.png)

https://github.com/finscn/Photoshop-Export-Layers-as-Images

**Comment by paazmaya** [comment]
:+1:

**Comment by AndrwM** [comment]
+1

**Comment by ptolp** [comment]
+1
