### ISSUE TITLE
Error on running script

### ISSUE THREAD

**Issue by Grechkovik** [jwa107/Photoshop-Export-Layers-to-Files-Fast#213]
OS - Microsoft Windows 10 Pro
Version - 10.0.19044 Build 19044

The two files were added to the 
/Program Files/Adobe/Adobe Photoshop VERSION/Presets/Scripts
location, but failed to open correctly

I'm assuming user error, but I'm stuck.

![Screenshot_114](https://user-images.githubusercontent.com/80915631/204571790-a56a41d4-b28b-4987-8272-8376f57a827c.png)

**Comment by antipalindrome** [comment]
@Grechkovik Sorry you're encountering a problem -- could you let me know what version of the script and photoshop you are on too? Additionally if you feel comfortable sharing a screenshot of the directory you are running the script from that could be helpful too. 

Also is this happening when you click on the script file, or when you click "run" from the dialog? If it's when you hit "run" in the dialog, could you include a screenshot of the settings you are running?

Thanks.

**Comment by Grechkovik** [comment]
Hi Hanna!

I kept trying, and learned it was user error!!
I've not really used github before, and it wasn't clear to me how you
download the files, so I did it one by one, right clicking the list and
downloading.

I saw a video where a person went to code, download zip file,
when I did it this way, it worked perfectly.

Thanks for your help,
and replying

:)
