### ISSUE TITLE
Failed to read the resource file 'Export%20Layers%20To%20Files%20(Fast)-progress_bar.json'

### ISSUE THREAD

**Issue by steve231293** [jwa107/Photoshop-Export-Layers-to-Files-Fast#229]
Hello there
Could you check & fix this issue, please?

Then select plugin file the waring showing:
![Frame 4362](https://github.com/antipalindrome/Photoshop-Export-Layers-to-Files-Fast/assets/7134267/7a019656-c5c2-4e6a-82d4-0f79291a5dc7)

I used Photoshop version 24.0.0

**Comment by steve231293** [comment]
@antipalindrome ,
Please help me 

Thank you in advanced.

**Comment by nirazul** [comment]
In order for me to work, I needed to do the following step (from the readme):

You can add the script to the Scripts menu by adding all of the script files to Photoshop > Presets > Scripts
- Windows: `/Program Files/Adobe/Adobe Photoshop VERSION/Presets/Scripts`
- Mac: `/Applications/Adobe Photoshop VERSION/Presets/Scripts`

**Comment by steve231293** [comment]
@nirazul. That's right, thank you for you reply
