### ISSUE TITLE
Freezes up on Photoshop CS6 (v13.0.6 x64), OS X Yosemite

### ISSUE THREAD

**Issue by jericho1ne** [jwa107/Photoshop-Export-Layers-to-Files-Fast#30]
I've made sure to copy the JSX file and 2xJSON files to the appropriate location.  Photoshop froze up both times I've tried it, had to force quit.

Error log here:
Http://jsfiddle.net/abtyw3u2/

Cheers!

**Comment by groxor** [comment]
The same thing happens to me. I've used your script before in Mountain Lion / Photoshop CS6, and it worked perfect. Since I use Yosemite, the same script freezes up once I press "Run". I have to Force Quit. My file has only 10 layers, 300 x 300 px @ 72 dpi.

**Comment by skjorn** [comment]
Looks like a Photoshop platform specific issue. I need someone to trace it. Comment out the export function in main(), try if it passes. Then go inside the function and do the same piece by piece until it's clear which line is responsible.

**Comment by AdamDrobotij** [comment]
Crashes for me as well on CC 2014, Yosemite. The initial crash occurs on line 525, on win.show() of showProgressBar(). Any ideas?

**Comment by AdamDrobotij** [comment]
Actually, if I comment out that line, the script seems to work fine. Just no progress par shows up.

**Comment by skjorn** [comment]
If you uncomment the line and run the script on a PSD with 20+ layers, does the dialog show? Or does it crash right away?

**Comment by AdamDrobotij** [comment]
The script seems to work fine as-is (with the line not uncommented) on PSDs with 20+ layers, but crashes on PSDs with less.

**Comment by skjorn** [comment]
Please, try the latest update. I'm not sure what the exact cause is, but I removed the difference between processing few and many layers. Let's see if it helps.

**Comment by skjorn** [comment]
Any news?

**Comment by groxor** [comment]
Runs perfect already! Thanks!!!!

**Comment by skjorn** [comment]
No problem. Would be nice to have also reports from others, but I'm gonna assume it's fixed and close these bugs. If anyone still experiences the issue, they can report it again.

**Comment by AdamDrobotij** [comment]
I just wanted to let you know that the new version of the script works for me, as well. Thank you for you work!

**Comment by skjorn** [comment]
Great, thanks for info!
