### ISSUE TITLE
CS6 Freezes when using Smart Objects

### ISSUE THREAD

**Issue by eschelar** [jwa107/Photoshop-Export-Layers-to-Files-Fast#35]
Fantastic little script you've got here. I've used it in testing and found it extremely intelligently designed. I particularly like the ability to keep the bottom layer as a constant, the fact that the naming isn't odd like the default one is, and it doesn't trim by default (who the heck wrote that script anyhow?)

This is exactly how I am using it. I've got 60 icons which are .ai objects in a PSD as smart objects. The graphics girl can then open the object in AI where she prefers to work and I can remain in PS. Then I can export all layers in the blink of an eye. Zoom.

However, when I have smart objects in the file, PS hangs immediately and becomes totally unresponsive. I made a test file that was just a few hundred KB with only 4 layers to test with. When exporting after rasterizing all the layers, it spits them out cleanly. When having a *single* smart object, the hang occurs.

I tried 3 times with each variable and it was 100% repeatable.

Note that the workaround is to rasterize all smart objects prior to running the script. There's a bit of preparation required (ie deleting extraneous background layers), so this isn't the end of the world, but there's 3 of us that use this file and it's worrisome to think that the file might get... knackered if someone accidentally saved on the way out (yes I've done that by accident before).

Using Win7 64, Production Premium CS6 package.

-k

**Comment by jwa107** [comment]
Thank you for information and detailed steps to reproduce. We'll try to take a look at this when we have some time. Thank you.

**Comment by skjorn** [comment]
Yes, interesting. I'll try to test it in CS2.

**Comment by skjorn** [comment]
@eschelar Tested exporting smart objects with a simple image, PSD and AI. All runs fine in CS2 under Win7, so the only conclusion is that Adobe broke something in later versions. There's nothing fancy going on with smart objects in the script itself. Is their default script working for you?

**Comment by eschelar** [comment]
Yes, the default script works. Sucks though. Yours is vastly superior.

Your script works fine too. It only breaks when there are smart objects.

Good call on testing PS and AI smart objects, I also tested these, but forgot to mention details. I also tried placed PNG source smart objects.

I will try this on some different computers. I only have CS6 though (one is master collection from the net, one is my own CS6 from Production Premium - on PC and my laptop).

I can do a camstudio video if you want me to show it. Would be good to get outside confirmation though from another user.

**Comment by skjorn** [comment]
@eschelar So if I understand it correctly, the default script exports smart objects just fine and ours hangs? That's weird. That could be the faster ActionManager code that collects layer info, depending on when the hang occurs. I think I will try and borrow the CS6 edition, since I have Win7, and test it there. Could you post a link to your testing file so I can verify?

**Comment by skjorn** [comment]
Ok, just tried Ps CS6 13.0.1 x64 Extended on Win7 -- one regular layer, one AI smart object via "Place..." -- and it worked no problems. The progress bar didn't update much, but that's normal in Ps. They never managed to make it work decently across all platforms.

@eschelar So I'll definitely need your test file, and the video would be helpful as well.

**Comment by eschelar** [comment]
I'll see what I can whip up for you. I tested with 3-4 different files, all built on the fly for testing purposes. All exported fine after rasterizing the smart objects. All failed when smart objects were present. 

Will update you when I'm back in the office tomorrow.

**Comment by eschelar** [comment]
Actually, I had quite a lot of trouble with this script today where it wasn't working even in ways that worked 100% reliably the other day. After a few tries, it started working properly though - except for the bug I mentioned. It seems that running it from the scripts folder is 60-80% likely to not work at all than if I just load it via the "browse" option. That might be a good indicator that there is something about my description of the problem that is missing some important detail.

But after a few tests, I did manage to get some repeatable results.

While I was rendering down the camstudio vid, I repeated the tests and continued to get a high rate of failure even when using rasterized pngs when using the script *specifically* from the menu (installed to the scripts folder in adobe).

The video shows these steps:
#1 - running the normal method
#2 - running in a way that works reliably - rasterizing the smart objects first, then running from the "Browse" part of the menu
#3 - running the same way, but not rasterizing first, hangs.
#4 - running from the menu, not rasterized (although this method freezes 60% or more of the time with rasterized layers).

I spared you the long wait, but I have given it more than 10 minutes to recover and no movement. As you can see, the response is very quick if it works properly.

As you can see, the computer I'm running it on is not remarkable, but quite capable. i5, 16gb, running from SSD etc... I don't think it's a problem with the machine.

I will do more testing with my laptop and home PC later on too.

**Comment by skjorn** [comment]
Judging by your video, the progress bar just doesn't appear sometimes. Relation to smart objects could be a coincidence. Please, try the recent update; it might help.

Thanks for your time and a thorough bug report, by the way.

**Comment by eschelar** [comment]
Thanks for looking into it. The progress bar shows up quickly and the process completes in under 20 seconds ordinarily. When it fails, it will not show up even if I leave the computer for 10 minutes and come back. There are also no files saved.

I have successfully used it without smart objects for several iterations with a 54 layer image file (200x200px) with the same results. Under 30 seconds with all smart objects rasterized, no movement at all with even one smart object.

Having said that, I have no idea how to proceed with troubleshooting or meaningful communication about this. Perhaps just log it in as a potential issue and if anything else happens, maybe it will be a helpful sign post.

Thanks again for your fine work in putting this plugin together.

**Comment by skjorn** [comment]
So no luck even with the yesterday's "fix"? I meant "the recent update" of this script.

**Comment by eschelar** [comment]
Oh, I didn't realize it was that recent. :)

I'll give it a shot when I'm back in the office. Probably later in the day as I have a deadline for 1:30pm for a big project.

**Comment by skjorn** [comment]
Any news?

**Comment by eschelar** [comment]
Sorry about the wait, got pulled away to some other projects for a while.

This recent update seems to have cleared everything up. No problem at all, approximately 45 seconds to export 52 layers in a 200x200 size.

Simply could not ask for anything better. Well - except maybe to have an ordinal number prefix option... but I don't even need this for this project.

Stellar work. Thank you again!

**Comment by skjorn** [comment]
Marvelous. Enjoy then :-)
