### ISSUE TITLE
Photoshop CC 2014 freezes 

### ISSUE THREAD

**Issue by iwanno** [jwa107/Photoshop-Export-Layers-to-Files-Fast#36]
Great work you guys have done here!

Unfortunately i can't get the script to work in Photoshop CC 2014 15.2.2 release or the older CC version 14.2.2. It keeps freezing when i press run. Photoshop freezes completely and the mouse shows a loading icon (which still moves).

Im running on an Imac with Yosemite 10.10.1.

Please let me know! Realy looking forward to use this.

Kind regards,
Iwan

**Comment by jwa107** [comment]
Can you try doing the following and let me know if that fixes it for you?
https://github.com/jwa107/Photoshop-Export-Layers-to-Files-Fast/issues/30#issuecomment-72060517

Thanks

**Comment by iwanno** [comment]
Yes, that seems to work so far :+1: 

I commented out line 523 and 524:

	//win.show();
	//repaintProgressBar(win, true);
}

**Comment by skjorn** [comment]
Assumed to be fixed. If you still experience the issue, please report it again.
