### ISSUE TITLE
Adjustment layer not saving.

### ISSUE THREAD

**Issue by sanwarhaider** [jwa107/Photoshop-Export-Layers-to-Files-Fast#44]
Adjustment layers are not saving to file.

**Comment by skjorn** [comment]
Yes, because usually there's nothing to save. What do you have in mind?

**Comment by sanwarhaider** [comment]
but an adjustment layer can change the background layer color also. so if color fill layer can save to new file why not adjustment layer.

**Comment by skjorn** [comment]
I don't understand you very well. There are all kinds of adjustment layers. If we speak about "solid fill", "gradient" or "pattern fill", they save just fine. I just tried. Everything else pretty much modifies what's underneath them -- there is no useful content to save by itself. Like sunshine. Can you photograph sunshine, for example? You can shoot a window reflecting sunshine, or beautiful colours in the sky, objects lit by it... But a picture of pure light radiation is nothing at all.

So unless you merge an adjustment layer or combine it with something, it has no effect. Nothing to save.
