### ISSUE TITLE
The UI lost   the description of options

### ISSUE THREAD

**Issue by finscn** [jwa107/Photoshop-Export-Layers-to-Files-Fast#46]
![2015-05-05 9 13 10](https://cloud.githubusercontent.com/assets/288367/7473188/b8c75a4e-f36b-11e4-9260-cd1413f7e8af.png)

The space of Panel is big enough , but the descriptions became  "..."

**Comment by skjorn** [comment]
I added more space for the controls. Please try it now. I don't have it on Mac, so I can't fix it all. Only what you mentioned.
