### ISSUE TITLE
Help, exporting groups?

### ISSUE THREAD

**Issue by clickstan** [jwa107/Photoshop-Export-Layers-to-Files-Fast#48]
I recently found this nice script, but when running it, I couldn't get it to export whole groups.

Please tell me how I could export all selected GROUPS, with one png file PER GROUP. This would save me hours of time, if it worked. 

Here are the groups I'd like exported:
![screen shot 2015-05-15 at 1 11 46 pm](https://cloud.githubusercontent.com/assets/8376113/7657932/0cb0d56e-fb04-11e4-9138-2d63b1d91460.png)

I'd like there to be one combined PNG per group, (so 10 pngs total) but after playing around with the settings, I couldn't achieve this. Please tell me how I could do this, or if it's not possible, please add this feature! 

THanks, Stan

**Comment by jwa107** [comment]
Stan,

This is currently not a feature. The point of the script it to export every layer individually.
It looks like you are using PhotoshopCC so you should just use their built in method to export layer groups as images.

https://helpx.adobe.com/photoshop/using/generate-assets-layers.html#Generate%20image%20assets%20from%20layers%20or%20layer%20groups

**Comment by clickstan** [comment]
Alright, thanks. j7e6]

**Comment by skjorn** [comment]
See feature request #21.
