### ISSUE TITLE
Become Indexed Files?

### ISSUE THREAD

**Issue by stooni** [jwa107/Photoshop-Export-Layers-to-Files-Fast#49]
I have tested and i become only rgb Files not png indexed!

Can these change?

-stooni

**Comment by jwa107** [comment]
I don't really understand. Could you clarify? Of if it's too hard to do in English you may use German as I can understand that too.

**Comment by skjorn** [comment]
Png indexed is PNG-8 format. You have to export them as such. Just select it in the drop box.
