### ISSUE TITLE
Progress bar resource is corrupt

### ISSUE THREAD

**Issue by problematxc** [jwa107/Photoshop-Export-Layers-to-Files-Fast#54]
I know that <a href="https://github.com/jwa107/Photoshop-Export-Layers-to-Files-Fast/issues/47">somebody already had this problem before</a> but I've tried re-downloading it several times and I keep getting this error: 
![capture](https://cloud.githubusercontent.com/assets/12841120/8101181/74d7930a-1047-11e5-9bf7-474f7790cf55.JPG)
<sub>[Error: Progress bar resource is corrupt! Please, redownload the script with all files.]</sub>

**Comment by skjorn** [comment]
Windows 8 or higher by the looks of it. Try replacing your file with this and tell me if it helps: http://www.equinoxcreations.com/download/progress_bar.json

**Comment by problematxc** [comment]
No, the error is still appearing ((unless I <i>wasn't</i> supposed to replace the progress_bar file with that))

**Comment by skjorn** [comment]
Then post a link to your progress_bar.json here. I'll take a look.

**Comment by problematxc** [comment]
http://hastebin.com/odevutoyis.sm

**Comment by skjorn** [comment]
Not very helpful as the service you used already processed the file on its own. I needed the original file. But never mind, it looks like you've got the right content, so last try: http://www.equinoxcreations.com/download/progress_bar.json Please download again and replace your current version. Notice if the error you're getting still mentions the "progress bar" or something else.

**Comment by LevyWilson** [comment]
I'm getting the error as well, even with the new progress_bar file you posted 2 weeks ago. Running Windows 7 with Photoshop CS6
![2015-06-28 20_26_54-artifactsinc_pnp psd 100 truck rgb_8](https://cloud.githubusercontent.com/assets/10651328/8399079/0303f4f4-1dd4-11e5-8ed0-d3eda5520b0f.png)

**Comment by skjorn** [comment]
I have no issues with Ps 6 in Windows 7. It looks like there's something wrong with your Ps installation.

**Comment by bizkid1** [comment]
I am also having the same issue with it using CS6 on Win 7 64-bit.  If it's something with PS, what clears it up?

**Comment by patryk-gruszka** [comment]
Same issue here - Windows 10 64-bit. Restart of application usually helps for short time. This error occurs irregularly and i can't find pattern to call it.

**Comment by jwa107** [comment]
Unless someone else experiences this an can provide more information I will keep this closed. We are unable to reproduce this with the hardware/software we have on hand.
