### ISSUE TITLE
Use top layer instead of lowest layer

### ISSUE THREAD

**Issue by thisisbbc** [jwa107/Photoshop-Export-Layers-to-Files-Fast#55]
Hi,

First of all I want to point out that this script is fantastic and that it saved us quite a lot of time. We use it to generate mockups so it was awesome to be able to iterate through logos to our products.

However this time, we would like to show a new product so we need to add the logo on all of our canvas. So far it seems that this is impossible.

The expected result is the exact same logic, iterate through visible layers for example, but instead of keeping the lowest layer as a background, it would keep the highest layer as an overlay.

Any samaritan can help us with this?

Cheers,
B

**Comment by skjorn** [comment]
That's in fact possible with the newest version. Just put everything you need to iterate through in a group and select the group. Then choose "Exported selected". It has a limitation of exporting all layers regardless visibility, but in general the use case is covered (with a bit more potential work).
