### ISSUE TITLE
Save for Web

### ISSUE THREAD

**Issue by dJunkyKode** [jwa107/Photoshop-Export-Layers-to-Files-Fast#58]
Hello awesome contributors to the virtual world!

How about adding the option to export each layer as web safe or something similar that can dramatically reduce the file sizes but keep the quality of the images?

**Comment by djdeeles** [comment]
Save for Web nice idea. Really use full for me.

**Comment by dJunkyKode** [comment]
Thank you for your comment djdeeles, I really hope this becomes a feature in the near future!

**Comment by Garconis** [comment]
That's the one big thing missing. Save For Web would be stellar!

**Comment by jwa107** [comment]
The script uses Save For Web and you can adjust image quality in the dialog.
