### ISSUE TITLE
dialog.json

### ISSUE THREAD

**Issue by TrySound** [jwa107/Photoshop-Export-Layers-to-Files-Fast#61]
Add double quotes around names please. This is not valid JSON and looks here ugly.
https://github.com/jwa107/Photoshop-Export-Layers-to-Files-Fast/blob/master/dialog.json

**Comment by skjorn** [comment]
As long as it's parsed by the Photoshop and does what it needs to, I don't really care. The convention was chosen according to the Ps documentation. If it really bothers you so much, why don't you add the quotes yourself, test it and then make a push request? I'd be happy to review and merge it if it works. It's github -- everyone can contribute.
