### ISSUE TITLE
Choice of underscores or hyphens

### ISSUE THREAD

**Issue by wesort** [jwa107/Photoshop-Export-Layers-to-Files-Fast#63]
This is a fantastic script and has already made my life a lot easier when prepping images for an e-commerce site. I too found the native 'export layers to files' script slow.

However, I'd prefer to have spaces in layer names replaced by hyphens instead of underscores in the resulting file name (apparently hyphens are better for SEO). I was able to do this by changing line 2189 in `Export Layers To Files (Fast).jsx` 

Would you consider adding the choice of underscores or hyphens?

**Comment by jwa107** [comment]
I'm glad you were able to change that line in the code yourself. We could definitely consider adding a field that lets you choose which character to use as a delimiter.

**Comment by MissFerrety** [comment]
@jwa107 I just tried out this script for the first time. Very cool. This was my immediate first instinct upon viewing the results, so please consider this feature request upvoted.

**Comment by jwa107** [comment]
This is now live, give it a shot.
