### ISSUE TITLE
Feature Request: Limit Trim/Add Transparency/Padding

### ISSUE THREAD

**Issue by KamiKaze425** [jwa107/Photoshop-Export-Layers-to-Files-Fast#64]
Not sure how useful this is to everyone. But there are times in Unity3D where an image trimmed all the way to the edge has some weird bleed. One solution is to add a pixel or two of transparency all around.
Would it be possible to do something like "Trim Transparency" but with padding? So it will basically trim and add x amount of pixels of transparency,

**Comment by finscn** [comment]
+1  .    I need this feature too
