### ISSUE TITLE
Error -36: Not Implimented

### ISSUE THREAD

**Issue by Clairvoire** [jwa107/Photoshop-Export-Layers-to-Files-Fast#68]
I got to run the script once, and it completed on exporting 16 layers (visible only, no trim, png-24), but it didn't actually create any files in when I checked after running it.  The directory I used was  "F:/art/output" if it matters

After this, I now get the following message when I run the script, and restarting photoshop CS4 doesn't help, nor does redownloading the script:

Error -36: Not implemented.
Line: 1143
->
formatOptRoot.quality.notify("onChanging");

(Thank you for the script by the way, this is going to be immeasurably helpful!)

**edit**: I commented out this one line and the script now runs as it should, wunderbar!

**Comment by arbolitoloco** [comment]
I get the same behavior after running once in CS4 64bit.

**Comment by Boycce** [comment]
I get this also

**Comment by filip-van-hoeckel** [comment]
I had the same experience: it worked once beautifully, then produced an error when running on the same file. Please advise, thanks.

**Comment by overtheresomewhere** [comment]
Another person here with the same issue. Only ran the script once successfully before this error appeared.

**Comment by skjorn** [comment]
Should be fixed by catching the error that happens when applying stored settings, but the settings will revert to default every time :-(

**Comment by exAntares** [comment]
Same issue again, different line (1372) I just commented that line to keep working.
Looks like "formatOptRoot.quality.notify("onChanging");" is not supported on CS4
