### ISSUE TITLE
how about exports based on layer groups?

### ISSUE THREAD

**Issue by jeancallisti** [jwa107/Photoshop-Export-Layers-to-Files-Fast#69]
Hello, as suggested by the project's homepage I'm using the tracker to post a suggestion:

There's a tool available on MacOS only, not free, called "Slicy", which does exactly what this tool does, except it allows you to export one PNG file (or other formats) _per layer_. The name of the exported PNG file is the actual name of the layer.

 It becomes really interesting when you know that it can also create exported files _per layer groups_. If your layer group is called "image.png", then it exports this group as file "image.png".

This is a very useful automation feature for exporting composited images (for example in one PSD file you can store all the bits of your website home page: buttons, background, icons, etc.).

It would be really, really cool if you guys did that for PC. From what I see you already have it 90% implemented, it's just missing the icing on the cake.

**Comment by jwa107** [comment]
So I'm not entirely sure which part of this is the suggestion.

This script does export a png per layer, and you can choose to export the images as the layer name.

As far as exporting layer groups as images, this is something already available in Adobe CC. I don't really see a reason to reproduce this particular functionality as theirs works really well.

**Comment by jeancallisti** [comment]
The suggestion is to combine : 
1) the ability to export automatically individual layers as images
2) the ability to export layer groups as images.

- This tool does #1 but does not do it for layer groups, only individual layers. 
- Adobe CC does #2 but (unless I'm mistaken) does not do it automatically, hence not allowing batch processing.

Believe me, if Slicy can make money out of this feature, it means it's really useful for a lot of people.
