### ISSUE TITLE
How to Keep spaces?

### ISSUE THREAD

**Issue by Newyears1978** [jwa107/Photoshop-Export-Layers-to-Files-Fast#75]
I checked keep spaces but I notice it adds dashes. I can't find any settings for "dashes" in settings as you suggest to check "Save for Web" settings.

**Comment by skjorn** [comment]
In CS6 turn off Unix and any other possible compatibility (also don't forget to check "Allow spaces" in the script itself):

![no_dashes](https://cloud.githubusercontent.com/assets/7663015/12247915/81703d98-b8b6-11e5-883b-c9e30f952a77.jpg)
