### ISSUE TITLE
How do we save masked layers?

### ISSUE THREAD

**Issue by satyamsaxena0786** [jwa107/Photoshop-Export-Layers-to-Files-Fast#76]
Hi jwa107, thanks for writing this super script! We need your help though - 

We're running the script and exporting individual images. Thing is, since all images are masked to one image, exporting them as individual layers takes the mask away. Essentially we're left with blanks =(

Is there any way to tell photoshop to leave the masked image alone? Maybe we could lock the layer, and tell photoshop to NOT unselect and export the locked layer. 

Please let us know how to do this, or if such a script can solve this. 

Thanks!
SS
![photo shop](https://cloud.githubusercontent.com/assets/9412432/12530776/950c2ee0-c20f-11e5-9fc2-6300af90eeb7.jpg)

**Comment by agence104** [comment]
Id like to follow up on this issue.

Would it be possible to keep the clipping mask in place upon exporting?

**Comment by skjorn** [comment]
Hi, unfortunately exporting layers and applying a mask to each of them is not possible by using only this script. You can copy the mask and merge it with each layer manually though. Not ideal, but it works... 

The thing is, the script treats the mask as a separate layer as well as other layers as unrelated to each other. So only one layer is switched on when exporting. It can leave a background under/over, but it can't apply masks. There's only one thing you might try -- select all visible layers except the mask, leave the mask visible, choose "Export selection", run the script and see if it works. If not, you're out of luck ;-)
