### ISSUE TITLE
How to save layers in a group as a single image while using this script?

### ISSUE THREAD

**Issue by enthuviv1** [jwa107/Photoshop-Export-Layers-to-Files-Fast#79]
There is no option if a user wants to save multiple layers of a group as a single image.

**Comment by skjorn** [comment]
You're right, there's no such option. The feature is not supported at the moment.

**Comment by enthuviv1** [comment]
Will u plz provide functionality for this feature. I shall be highly obliged.

Or is there any other script for doing this?

**Comment by skjorn** [comment]
Maybe in the future. For now I usually use: Duplicate -> Merge required groups manually -> Export via script.

**Comment by enthuviv1** [comment]
actually there are large number of groups, and merging them manually is very difficult.

**Comment by skjorn** [comment]
Sorry, can't help you there. You can try Photoshop CC -- apparently it's supported there -- might be a bit slower, but probably will get you where you want, or some of the forks. Have a look at them via the "Fork" button at the top right corner of this page.

**Comment by Kajskk** [comment]
enthuviv1, I have the exact same question, I wish to export the topmost group in said group-tree (and merge all sub groups/nested groups). 

Did you happen to find a script that does this?
