### ISSUE TITLE
Reflect the Layer Folders Structure

### ISSUE THREAD

**Issue by Zacchino** [jwa107/Photoshop-Export-Layers-to-Files-Fast#81]
Hello @jwa107 
Can you please, oh please, add an option where the plugin extract the PSD Layer Folders and Sub-folders structure the same way we arranged it in our Iconography.psd file ?

So that it reflects our work, and make it easy for developers to understand which icons belongs to which view ?
Example : 
Iconography.psd (Main Folder)  
  Home (SubFolder)
  ├ Search.png
  ├ Menu.png
  ├ Pencil.png
  └ Flag.png
  Login (SubFolder)
  ├ Facebook.png
  ├ Twitter.png
  ├ LinkedIn.png
  └ E-Mail.png

I'm sure a vast majority will find it useful.

**Comment by apauriche** [comment]
i did it here : 
[](https://github.com/jwa107/Photoshop-Export-Layers-to-Files-Fast/pull/86)

**Comment by Zacchino** [comment]
Hello Apauriche!
Thank you I saw the commit and it sounds great.

But I tested it (I ticked "Create Sub folders"), and it doesn't create the folder structure as expected... Maybe did I missed something?

**Comment by apauriche** [comment]
Hi Isaac,

Here some screen of the photoshop structure :

[image: Images intégrées 1]

Here the folder structure created :

[image: Images intégrées 2]

I will remove the "@2x" suffix i think this is the problem you get ?


2016-04-25 14:07 GMT+02:00 Isaac Slama <notifications@github.com>:

**Comment by apauriche** [comment]
Here it go i pushed it in the subfolders branch.

2016-04-25 14:44 GMT+02:00 Anthony Pauriche <anthony.pauriche@gmail.com>:

**Comment by apauriche** [comment]
Hello have you tried ?

2016-04-25 14:51 GMT+02:00 Anthony Pauriche <anthony.pauriche@gmail.com>:

**Comment by skjorn** [comment]
Done.
