### ISSUE TITLE
Exporting nested group instead of layers?

### ISSUE THREAD

**Issue by bardtian** [jwa107/Photoshop-Export-Layers-to-Files-Fast#83]
Hi,
Great creation!

My psd file with a layer structure like this:
https://i.gyazo.com/0ddddcf5821e030a463b8829aff17daf.png

What I am thinking is to export all the greed arrow groups but not red groups.
Is this possible?

I already tested the script, the trouble is if I selected the group named **Works**, and it exports all the layers. Only if I selected **Saiboat**, and it exports the 5 groups which is right.

I wonder if this works for exporting every nested groups instead of exporting every layers?

**Comment by skjorn** [comment]
Hi, thanks.

> What I am thinking is to export all the greed arrow groups but not red groups.
Is this possible?
Yes, you describe how in the next sentence, given the script option "Selected group" is selected.

> I wonder if this works for exporting every nested groups instead of exporting every layers?
I don't understand.

**Comment by bardtian** [comment]
Sorry, my poor language.
This great script does almost perfect to me, but something is different in my project and I guess this is not a special case.
 
 
### My project
I have a big project that will keep growing with each passing day in both main arts and backgrounds, each art-work maybe have over 10 different background styles(the background is not an issue).
It looks like this image:
![Overview](http://i.imgur.com/Dhr8Dg0.jpg)

God blessed I know I can manage all art-works in a single .psd file, I sort them out by using nested folders as category.
It looks like this image:
![Categories](http://i.imgur.com/BHxZ0cJ.jpg)


### The inconvenience
The trouble is not every art-work in my psd are single layer, a few of  them are single layer and lots of them are separated by layers. I can’t merge them since some of them may be updated later when need.
The difference between single layer art-work and multi layers art-work:
![The inconvenience](http://i.imgur.com/vMEZH04.jpg)

So what can I do, I can just manage every single art-work in an exclusive folder, I named every end folder the art-work's name.


### The suggestion
If the script has an option for exporting the **end**(last) **folders** instead of every single layers under the selected folder, and names the exporting files the end folder’s name, then it will be perfect in this case:)

**Comment by skjorn** [comment]
Hi, that's a much better explanation ;-)

> If the script has an option for exporting the end(last) folders instead of every single layers

You're right, it can't do that. The feature's been requested many times, but there's just not enough development effort at the moment. Thank you for your suggestion though. It definitely matters. It shows us what functionality people want from our script, so we might add it later.

In your case specifically though, there's help, I think. Group your "multi layer artworks" into Smart Objects. Then they will export as single layers ;-)
