### ISSUE TITLE
Help me, I want Make highest layers is background

### ISSUE THREAD

**Issue by phoenixjutom** [jwa107/Photoshop-Export-Layers-to-Files-Fast#84]
Dear you,
I like this script and want to: "Make highest layers is background". Because I want to this layer is always have in export file.

Can you help me?

**Comment by skjorn** [comment]
Hi, do this: put everything except the highest layer in a group (folder), keep the highest layer visible, select the folder in the layers panel, run the script with the option "Selected group" selected. That's it.

Drawback -- it will export everything in the selection -- visible or invisible. If you need to export only a subset, split layers to groups accordingly if possible, or use duplicate, remove what you don't want to export and do the process above.

Hope this helps.
