### ISSUE TITLE
Progress bar is corrupt.

### ISSUE THREAD

**Issue by shellybellstark** [jwa107/Photoshop-Export-Layers-to-Files-Fast#87]
I've tried everything to fix this-- I've gone into the code, redownloaded the script four times, even changed PS versions. I can't get any of my work done! Any help would be appreciated.

picture of the error:
![image](https://cloud.githubusercontent.com/assets/19510163/15451042/631363fa-1f7e-11e6-8349-0b80daa98bf5.png)

picture of the progress bar code:
![image](https://cloud.githubusercontent.com/assets/19510163/15451043/7c404e7e-1f7e-11e6-8ba3-bf5d2e20a086.png)

**Comment by formerhermit** [comment]
I also have this issue.

**Comment by Lotsanew** [comment]
I have that same issue, and @soychicka's solution doesn't work for me.

**Comment by matiasballadares** [comment]
** @soychicka**'s solution doesn't work for me either. I tried it but it just ended up telling me there was no progress_bar.json file but it was right there! Help please!

**Comment by jwa107** [comment]
We've had a lot of changes recently, if this is still an issue for some of you please file a new issue with the OS/PS versionn
