### ISSUE TITLE
The script wouldn't run.

### ISSUE THREAD

**Issue by megadisia** [jwa107/Photoshop-Export-Layers-to-Files-Fast#93]
Any time I try to run the script, this error appears:
[image](https://cloud.githubusercontent.com/assets/21129238/17818617/124f3190-664d-11e6-9249-8fdf0001b9a2.png)
In fact, the script worked just once, but not anymore.

**Comment by skjorn** [comment]
Hi, try it now. It should run, but your previous settings won't be restored unfortunately.
