### ISSUE TITLE
error -36: Not implemented line 1320

### ISSUE THREAD

**Issue by RueStudio** [jwa107/Photoshop-Export-Layers-to-Files-Fast#94]
->formatOptRoot.quality.notify("OnChanging");

It ran once perfectly... now I get this error every time I try to access it... it seems to jump right into the progress bar as if trying to run it without giving me a GUI.

Like it stuck in START mode.

Help!

**Comment by skjorn** [comment]
Hi, try it now. It should run, but your previous settings won't be restored unfortunately.
