### ISSUE TITLE
Highest layer repeated on each exported layer

### ISSUE THREAD

**Issue by gekkoh** [jwa107/Photoshop-Export-Layers-to-Files-Fast#96]
Please add option to have the highest positioned layer to be visible on each export. For example a logo that you want to be on top of each exported layer.

Thanks! 👍

**Comment by gloofer** [comment]
I give my vote to this one. A check box with the label: "Treat topmost layer as an overlay" perhaps. I can see a lot of situations where an overlay (whether it is a logo, a semi transparent pattern, a mask or alike ) that is visible on each export would come in handy.

**Comment by Raccooncity1998** [comment]
same here... and also merge group as one single image
