### ISSUE TITLE
Same problem again

### ISSUE THREAD

**Issue by megadisia** [jwa107/Photoshop-Export-Layers-to-Files-Fast#97]
Thank you, I guess you changed smth and the script worked again. But not the second time...
...again.
Well, I dragged and dropped the script firstly, the second time I moved the whole script folder in Photoshop's scripts folder to run the script right in the program. And it sent me the same thing as the previous time 
https://github.com/jwa107/Photoshop-Export-Layers-to-Files-Fast/issues/93. Redownloading doesn't help :'(

**Comment by jwa107** [comment]
Was it the same error or a different one?
